<a href="https://colab.research.google.com/github/GiovaniMicheloni/mlearning-w-python/blob/main/base_credito5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Base Credito com algoritmo SVM

In [1]:
!pip -q install yellowbrick
!pip -q install plotly

In [2]:
import pandas as pd
import seaborn as sns
import numpy as np
import plotly.express as px
import matplotlib.pyplot as plt

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [6]:
basecredito = pd.read_csv('/content/credit_data.csv')

In [9]:
basecredito[basecredito['age']<0]

clientid        income        age         loan  default
15        16  50501.726689 -28.218361  3977.287432        0
21        22  32197.620701 -52.423280  4244.057136        0
26        27  63287.038908 -36.496976  9595.286289        0

In [15]:
basecredito['age'][basecredito['age']>0].mean()

40.92770044906149

In [16]:
basecredito.loc[basecredito['age']<0, 'age'] = 40.92;

In [17]:
basecredito[basecredito['age']<0]

Empty DataFrame
Columns: [clientid, income, age, loan, default]
Index: []

In [19]:
basecredito.isnull().sum()

clientid    0
income      0
age         3
loan        0
default     0
dtype: int64

In [22]:
basecredito.loc[pd.isnull(basecredito['age'])]

clientid        income  age         loan  default
28        29  59417.805406  NaN  2082.625938        0
30        31  48528.852796  NaN  6155.784670        0
31        32  23526.302555  NaN  2862.010139        0

In [25]:
basecredito['age']=basecredito['age'].fillna(basecredito['age'].mean())

In [26]:
basecredito.loc[pd.isnull(basecredito['age'])]

Empty DataFrame
Columns: [clientid, income, age, loan, default]
Index: []

In [27]:
x_credit = basecredito.iloc[:, 1:4].values
x_credit

array([[6.61559251e+04, 5.90170151e+01, 8.10653213e+03],
       [3.44151540e+04, 4.81171531e+01, 6.56474502e+03],
       [5.73171701e+04, 6.31080495e+01, 8.02095330e+03],
       ...,
       [4.43114493e+04, 2.80171669e+01, 5.52278669e+03],
       [4.37560566e+04, 6.39717958e+01, 1.62272260e+03],
       [6.94365796e+04, 5.61526170e+01, 7.37883360e+03]])

In [28]:
y_credit = basecredito.iloc[:, 4].values
y_credit

array([0, 0, 0, ..., 1, 0, 0])

In [29]:
from sklearn.preprocessing import StandardScaler
scaler_credit = StandardScaler()
x_credit = scaler_credit.fit_transform(x_credit)
x_credit


array([[ 1.45393393,  1.36538093,  1.20281942],
       [-0.76217555,  0.5426602 ,  0.69642695],
       [ 0.83682073,  1.67417189,  1.17471147],
       ...,
       [-0.07122592, -0.97448519,  0.35420081],
       [-0.11000289,  1.73936739, -0.92675625],
       [ 1.682986  ,  1.14917639,  0.96381038]])

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
xcredito_treino, xcredito_test, ycredito_treino, ycredito_test = train_test_split(x_credit, y_credit, test_size = 0.25, random_state = 0)


In [34]:
xcredito_treino.shape, ycredito_treino.shape

((1500, 3), (1500,))

In [33]:
from sklearn.svm import SVC

In [60]:
svm_credit = SVC(kernel = 'rbf',random_state=1, C=2.0)
svm_credit.fit(xcredito_treino, ycredito_treino)

SVC(C=2.0, random_state=1)

In [61]:
previsoes = svm_credit.predict(xcredito_test)

In [62]:
from sklearn.metrics import accuracy_score, classification_report
accuracy_score(previsoes, ycredito_test)

0.988

In [63]:
print(classification_report(previsoes,ycredito_test))

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       438
           1       0.94      0.97      0.95        62

    accuracy                           0.99       500
   macro avg       0.97      0.98      0.97       500
weighted avg       0.99      0.99      0.99       500

