<a href="https://colab.research.google.com/github/GiovaniMicheloni/mlearning-w-python/blob/main/teste_regressaolinear.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip install plotly --upgrade

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.8/14.8 MB 40.7 MB/s eta 0:00:00
  Attempting uninstall: plotly
    Found existing installation: plotly 5.24.1
    Uninstalling plotly-5.24.1:
      Successfully uninstalled plotly-5.24.1


In [4]:
!pip -q install yellowbrick

In [8]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

In [9]:
df_saude = pd.DataFrame({
    'Idade': [18,23,28,33,38,43,48,53,58,63],
    'Custo': [871,1132,1242,1356,1488,1638,2130,2454,3066,4090]
})

In [10]:
df_saude

Idade  Custo
0     18    871
1     23   1132
2     28   1242
3     33   1356
4     38   1488
5     43   1638
6     48   2130
7     53   2454
8     58   3066
9     63   4090

In [18]:
xplano = df_saude.iloc[:,0]
xplano

0    18
1    23
2    28
3    33
4    38
5    43
6    48
7    53
8    58
9    63
Name: Idade, dtype: int64

In [17]:
yplano = df_saude.iloc[:,1]
yplano

0     871
1    1132
2    1242
3    1356
4    1488
5    1638
6    2130
7    2454
8    3066
9    4090
Name: Custo, dtype: int64

In [19]:
np.corrcoef(xplano, yplano)

array([[1.        , 0.93091958],
       [0.93091958, 1.        ]])

In [20]:
xplano.shape

(10,)

In [27]:
xplano = xplano.reshape(-1,1)
xplano.shape

(10, 1)

In [28]:
from sklearn.linear_model import LinearRegression
regressorplano = LinearRegression()
regressorplano.fit(xplano,yplano)

LinearRegression()

In [29]:
#b0 intercepta o eixo y
regressorplano.intercept_

np.float64(-558.9490909090912)

In [30]:
#b1 inclinaçao da reta
regressorplano.coef_

array([61.86787879])

In [31]:
previsoes = regressorplano.predict(xplano)
previsoes  #y=b0+b1*x1 valor=ponto que intercept+inclinação * idade

array([ 554.67272727,  864.01212121, 1173.35151515, 1482.69090909,
       1792.03030303, 2101.36969697, 2410.70909091, 2720.04848485,
       3029.38787879, 3338.72727273])

In [32]:
yplano

0     871
1    1132
2    1242
3    1356
4    1488
5    1638
6    2130
7    2454
8    3066
9    4090
Name: Custo, dtype: int64

In [45]:
xplano = df_saude['Idade'].to_numpy().reshape(-1, 1)

In [49]:
grafico = px.scatter(x = xplano.ravel(), y = yplano)
grafico.add_scatter(x = xplano.ravel(), y = previsoes, name ='Regressão')
grafico.show()