<a href="https://colab.research.google.com/github/GiovaniMicheloni/mlearning-w-python/blob/main/teste_regressaoarvore.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Regressão com arvore de decisão - plano de saúde(idade e custo)


In [1]:
!pip install plotly --upgrade

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.8/14.8 MB 52.1 MB/s eta 0:00:00
  Attempting uninstall: plotly
    Found existing installation: plotly 5.24.1
    Uninstalling plotly-5.24.1:
      Successfully uninstalled plotly-5.24.1


In [2]:
!pip -q install yellowbrick

In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px

In [13]:
df_saude = pd.DataFrame({
    'Idade': [18,23,28,33,38,43,48,53,58,63],
    'Custo': [470,520,630,830,1150,1530,2040,3080,5100,10100]
})

In [14]:
df_saude

Idade  Custo
0     18    470
1     23    520
2     28    630
3     33    830
4     38   1150
5     43   1530
6     48   2040
7     53   3080
8     58   5100
9     63  10100

In [15]:
xplano = df_saude.iloc[:,0]

In [16]:
xplano

0    18
1    23
2    28
3    33
4    38
5    43
6    48
7    53
8    58
9    63
Name: Idade, dtype: int64

In [17]:
yplano = df_saude.iloc[:,1]
yplano

0      470
1      520
2      630
3      830
4     1150
5     1530
6     2040
7     3080
8     5100
9    10100
Name: Custo, dtype: int64

In [18]:
np.corrcoef(xplano, yplano)

array([[1.       , 0.8199208],
       [0.8199208, 1.       ]])

In [20]:
xplano = df_saude.iloc[:,0].values.reshape(-1,1)
xplano.shape

(10, 1)

In [21]:
 from sklearn.tree import DecisionTreeRegressor
 regressor_arvore_saude = DecisionTreeRegressor()
 regressor_arvore_saude.fit(xplano,yplano)

DecisionTreeRegressor()

In [23]:
previsoes = regressor_arvore_saude.predict(xplano)
previsoes

array([  470.,   520.,   630.,   830.,  1150.,  1530.,  2040.,  3080.,
        5100., 10100.])

In [24]:
regressor_arvore_saude.score(xplano,yplano)

1.0

In [26]:
grafico = px.scatter(x = xplano.ravel(), y = yplano)
grafico.add_scatter(x = xplano.ravel(), y = previsoes, name ='Regressão')
grafico.show()

In [27]:
xtest_arvore = np.arange(min(xplano),max(xplano), 0.1)
xtest_arvore

<ipython-input-27-2f55ba6bf8bf>:1: DeprecationWarning:

Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)



array([18. , 18.1, 18.2, 18.3, 18.4, 18.5, 18.6, 18.7, 18.8, 18.9, 19. ,
       19.1, 19.2, 19.3, 19.4, 19.5, 19.6, 19.7, 19.8, 19.9, 20. , 20.1,
       20.2, 20.3, 20.4, 20.5, 20.6, 20.7, 20.8, 20.9, 21. , 21.1, 21.2,
       21.3, 21.4, 21.5, 21.6, 21.7, 21.8, 21.9, 22. , 22.1, 22.2, 22.3,
       22.4, 22.5, 22.6, 22.7, 22.8, 22.9, 23. , 23.1, 23.2, 23.3, 23.4,
       23.5, 23.6, 23.7, 23.8, 23.9, 24. , 24.1, 24.2, 24.3, 24.4, 24.5,
       24.6, 24.7, 24.8, 24.9, 25. , 25.1, 25.2, 25.3, 25.4, 25.5, 25.6,
       25.7, 25.8, 25.9, 26. , 26.1, 26.2, 26.3, 26.4, 26.5, 26.6, 26.7,
       26.8, 26.9, 27. , 27.1, 27.2, 27.3, 27.4, 27.5, 27.6, 27.7, 27.8,
       27.9, 28. , 28.1, 28.2, 28.3, 28.4, 28.5, 28.6, 28.7, 28.8, 28.9,
       29. , 29.1, 29.2, 29.3, 29.4, 29.5, 29.6, 29.7, 29.8, 29.9, 30. ,
       30.1, 30.2, 30.3, 30.4, 30.5, 30.6, 30.7, 30.8, 30.9, 31. , 31.1,
       31.2, 31.3, 31.4, 31.5, 31.6, 31.7, 31.8, 31.9, 32. , 32.1, 32.2,
       32.3, 32.4, 32.5, 32.6, 32.7, 32.8, 32.9, 33

In [28]:
xtest_arvore.shape

(450,)

In [29]:
xtest_arvore = xtest_arvore.reshape(-1,1)
xtest_arvore.shape

(450, 1)

In [30]:
grafico = px.scatter(x = xplano.ravel(), y = yplano)
grafico.add_scatter(x = xtest_arvore.ravel(), y = regressor_arvore_saude.predict(xtest_arvore), name ='Regressão')
grafico.show()

In [32]:
regressor_arvore_saude.predict([[40.6]])

array([1530.])